version: '3.8'

services:
  composer-assistant:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: composer-assistant
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      # Volumen para logs de nginx
      - nginx-logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


  # Servicio de desarrollo (opcional)
  composer-assistant-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: composer-assistant-dev
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      # Montar código fuente para hot reload
      - .:/app
      - /app/node_modules
    profiles:
      - dev

volumes:
  nginx-logs: 