version: '3.8'

services:
  composer-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: composer-assistant
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    volumes:
      # Volumen para logs de nginx
      - nginx-logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.composer-assistant.rule=Host(`composer-assistant.yourdomain.com`)"
      - "traefik.http.routers.composer-assistant.entrypoints=websecure"
      - "traefik.http.routers.composer-assistant.tls.certresolver=letsencrypt"
      - "traefik.http.services.composer-assistant.loadbalancer.server.port=80"

volumes:
  nginx-logs: 