version: '3.8'

services:
  composer-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: composer-assistant
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production 